apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: test-container
      image: nginx
      env:
        - name: NGINX_CONFIG
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: config.json
        - name: TEST_VAR1
          valueFrom:
            configMapKeyRef:
              name: another-map
              key: coswiecej 
      envFrom: 
      - configMapRef:
          name: from-env-file

