apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: "cars.192.168.189.128.nip.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cars-svc
            port:
              number: 80
  - host: "books.192.168.189.128.nip.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: books-svc
            port:
              number: 80

